<?php
defined('ABSPATH') || exit;

final class GOI_Core_DB {
 public static function tables(): array {
  global $wpdb; $p=$wpdb->prefix.'goi_';
  return [
   'organisations'=>$p.'organisations','countries'=>$p.'countries','regions'=>$p.'regions','country_metrics'=>$p.'country_metrics','trade_flows'=>$p.'trade_flows',
   'data_sources'=>$p.'data_sources', 'data_source_runs'=>$p.'data_source_runs','opportunities'=>$p.'opportunities','opportunity_sources'=>$p.'opportunity_sources',
   'opportunity_observations'=>$p.'opportunity_observations','procurement_records'=>$p.'procurement_records',
   'procurement_awards'=>$p.'procurement_awards','procurement_contracts'=>$p.'procurement_contracts',
   'procurement_documents'=>$p.'procurement_documents'
  ];
 }
 public static function install_schema(): void {
  global $wpdb; require_once ABSPATH.'wp-admin/includes/upgrade.php'; $t=self::tables(); $c=$wpdb->get_charset_collate(); $sql=[];
  $sql[]="CREATE TABLE {$t['organisations']} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,uuid char(36) NOT NULL,name varchar(255) NOT NULL,organisation_type varchar(50) NOT NULL DEFAULT 'company',country_code char(2) DEFAULT NULL,website_url text DEFAULT NULL,status varchar(30) NOT NULL DEFAULT 'active',created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY (id),UNIQUE KEY uuid (uuid),KEY country_code (country_code),KEY type_status (organisation_type,status)) $c;";
  $sql[]="CREATE TABLE {$t['countries']} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,iso2 char(2) NOT NULL,iso3 char(3) NOT NULL,name varchar(255) NOT NULL,official_name text DEFAULT NULL,capital varchar(255) DEFAULT NULL,region_name varchar(255) DEFAULT NULL,subregion_name varchar(255) DEFAULT NULL,income_group varchar(80) DEFAULT NULL,currency_code char(3) DEFAULT NULL,timezone varchar(64) DEFAULT NULL,latitude decimal(10,7) DEFAULT NULL,longitude decimal(10,7) DEFAULT NULL,status varchar(30) NOT NULL DEFAULT 'active',created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY (id),UNIQUE KEY iso2 (iso2),UNIQUE KEY iso3 (iso3),KEY status (status),KEY region_name (region_name)) $c;";
  $sql[]="CREATE TABLE {$t['regions']} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,uuid char(36) NOT NULL,country_id bigint(20) unsigned NOT NULL,parent_id bigint(20) unsigned DEFAULT NULL,name varchar(255) NOT NULL,region_type varchar(40) NOT NULL DEFAULT 'region',latitude decimal(10,7) DEFAULT NULL,longitude decimal(10,7) DEFAULT NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY (id),UNIQUE KEY uuid (uuid),KEY country_parent (country_id,parent_id),KEY name (name)) $c;";
  $sql[]="CREATE TABLE {$t['country_metrics']} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,country_id bigint(20) unsigned NOT NULL,metric_code varchar(80) NOT NULL,metric_year smallint unsigned NOT NULL,metric_value decimal(30,8) DEFAULT NULL,unit varchar(40) DEFAULT NULL,source_id bigint(20) unsigned DEFAULT NULL,source_record_id varchar(255) DEFAULT NULL,observed_at datetime NOT NULL,raw_payload_hash char(64) DEFAULT NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY (id),UNIQUE KEY country_metric_year (country_id,metric_code,metric_year),KEY metric_year (metric_code,metric_year),KEY source (source_id)) $c;";
  $sql[]="CREATE TABLE {$t['trade_flows']} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,reporter_country_id bigint(20) unsigned NOT NULL,partner_country_id bigint(20) unsigned DEFAULT NULL,trade_year smallint unsigned NOT NULL,trade_flow varchar(20) NOT NULL,hs_version varchar(20) DEFAULT NULL,hs_code varchar(20) DEFAULT NULL,commodity_name varchar(255) DEFAULT NULL,value_usd decimal(30,2) DEFAULT NULL,quantity decimal(30,6) DEFAULT NULL,quantity_unit varchar(40) DEFAULT NULL,source_id bigint(20) unsigned DEFAULT NULL,source_record_id varchar(255) DEFAULT NULL,observed_at datetime NOT NULL,raw_payload_hash char(64) DEFAULT NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY (id),UNIQUE KEY trade_observation (reporter_country_id,partner_country_id,trade_year,trade_flow,hs_version,hs_code,source_id),KEY reporter_year (reporter_country_id,trade_year),KEY partner_year (partner_country_id,trade_year),KEY hs_year (hs_code,trade_year),KEY flow_year (trade_flow,trade_year)) $c;";
  $sql[]="CREATE TABLE {$t['data_sources']} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,uuid char(36) NOT NULL,name varchar(255) NOT NULL,adapter_id varchar(80) DEFAULT NULL,owner_name varchar(255) DEFAULT NULL,source_type varchar(40) NOT NULL,country_code char(2) DEFAULT NULL,base_url text DEFAULT NULL,licence text DEFAULT NULL,reliability decimal(5,2) DEFAULT NULL,status varchar(30) NOT NULL DEFAULT 'active',last_sync_at datetime DEFAULT NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY (id),UNIQUE KEY uuid (uuid),KEY adapter_id (adapter_id),KEY country_status (country_code,status),KEY type_status (source_type,status)) $c;";
  $sql[]="CREATE TABLE {$t['opportunities']} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,uuid char(36) NOT NULL,external_id varchar(255) DEFAULT NULL,canonical_key char(64) DEFAULT NULL,title text NOT NULL,description longtext DEFAULT NULL,opportunity_type varchar(50) NOT NULL DEFAULT 'procurement',status varchar(30) NOT NULL DEFAULT 'open',country_code char(2) DEFAULT NULL,region_id bigint(20) unsigned DEFAULT NULL,buyer_organisation_id bigint(20) unsigned DEFAULT NULL,published_at datetime DEFAULT NULL,deadline_at datetime DEFAULT NULL,estimated_value decimal(20,2) DEFAULT NULL,currency_code char(3) DEFAULT NULL,url text DEFAULT NULL,latitude decimal(10,7) DEFAULT NULL,longitude decimal(10,7) DEFAULT NULL,source_updated_at datetime DEFAULT NULL,first_seen_at datetime NOT NULL,last_seen_at datetime NOT NULL,content_hash char(64) DEFAULT NULL,metadata longtext DEFAULT NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY (id),UNIQUE KEY uuid (uuid),UNIQUE KEY canonical_key (canonical_key),KEY deadline_status (deadline_at,status),KEY country_status (country_code,status),KEY buyer (buyer_organisation_id),KEY region (region_id),KEY content_hash (content_hash),KEY geo (latitude,longitude)) $c;";
  $sql[]="CREATE TABLE {$t['opportunity_sources']} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,opportunity_id bigint(20) unsigned NOT NULL,source_id bigint(20) unsigned NOT NULL,source_record_id varchar(255) DEFAULT NULL,source_url text DEFAULT NULL,observed_at datetime NOT NULL,raw_hash char(64) DEFAULT NULL,PRIMARY KEY (id),UNIQUE KEY opportunity_source (opportunity_id,source_id),KEY source_record (source_id,source_record_id)) $c;";
  $sql[]="CREATE TABLE {$t['data_source_runs']} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,source_id bigint(20) unsigned NOT NULL,run_uuid char(36) NOT NULL,started_at datetime NOT NULL,finished_at datetime DEFAULT NULL,status varchar(30) NOT NULL DEFAULT 'running',records_seen int unsigned NOT NULL DEFAULT 0,records_created int unsigned NOT NULL DEFAULT 0,records_updated int unsigned NOT NULL DEFAULT 0,records_rejected int unsigned NOT NULL DEFAULT 0,error_count int unsigned NOT NULL DEFAULT 0,cursor text DEFAULT NULL,error_summary text DEFAULT NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY (id),UNIQUE KEY run_uuid (run_uuid),KEY source_status (source_id,status),KEY started_at (started_at)) $c;";
  $sql[]="CREATE TABLE {$t['opportunity_observations']} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,opportunity_id bigint(20) unsigned NOT NULL,source_id bigint(20) unsigned NOT NULL,source_record_id varchar(255) DEFAULT NULL,observed_at datetime NOT NULL,content_hash char(64) DEFAULT NULL,payload longtext DEFAULT NULL,change_type varchar(30) NOT NULL DEFAULT 'observed',PRIMARY KEY (id),KEY opportunity_observed (opportunity_id,observed_at),KEY source_record (source_id,source_record_id),KEY content_hash (content_hash)) $c;";
  $sql[]="CREATE TABLE {$t['procurement_records']} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,opportunity_id bigint(20) unsigned NOT NULL,ocid varchar(255) DEFAULT NULL,procurement_method varchar(60) DEFAULT NULL,procurement_method_details text DEFAULT NULL,main_procurement_category varchar(80) DEFAULT NULL,additional_procurement_categories text DEFAULT NULL,planning_status varchar(40) DEFAULT NULL,tender_status varchar(40) DEFAULT NULL,tender_title text DEFAULT NULL,tender_description longtext DEFAULT NULL,tender_date datetime DEFAULT NULL,tender_period_start datetime DEFAULT NULL,tender_period_end datetime DEFAULT NULL,tender_value decimal(20,2) DEFAULT NULL,tender_currency char(3) DEFAULT NULL,number_of_tenderers int unsigned DEFAULT NULL,award_status varchar(40) DEFAULT NULL,contract_status varchar(40) DEFAULT NULL,ocds_version varchar(20) DEFAULT NULL,raw_payload_hash char(64) DEFAULT NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY (id),UNIQUE KEY opportunity (opportunity_id),UNIQUE KEY ocid (ocid),KEY tender_status (tender_status),KEY tender_end (tender_period_end),KEY procurement_method (procurement_method)) $c;";
  $sql[]="CREATE TABLE {$t['procurement_awards']} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,procurement_record_id bigint(20) unsigned NOT NULL,award_id varchar(255) DEFAULT NULL,title text DEFAULT NULL,status varchar(40) DEFAULT NULL,date datetime DEFAULT NULL,value decimal(20,2) DEFAULT NULL,currency_code char(3) DEFAULT NULL,supplier_organisation_id bigint(20) unsigned DEFAULT NULL,description longtext DEFAULT NULL,raw_payload_hash char(64) DEFAULT NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY (id),UNIQUE KEY record_award (procurement_record_id,award_id),KEY supplier (supplier_organisation_id),KEY status_date (status,date)) $c;";
  $sql[]="CREATE TABLE {$t['procurement_contracts']} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,procurement_record_id bigint(20) unsigned NOT NULL,contract_id varchar(255) DEFAULT NULL,title text DEFAULT NULL,status varchar(40) DEFAULT NULL,date_signed datetime DEFAULT NULL,start_date datetime DEFAULT NULL,end_date datetime DEFAULT NULL,value decimal(20,2) DEFAULT NULL,currency_code char(3) DEFAULT NULL,supplier_organisation_id bigint(20) unsigned DEFAULT NULL,description longtext DEFAULT NULL,raw_payload_hash char(64) DEFAULT NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY (id),UNIQUE KEY record_contract (procurement_record_id,contract_id),KEY supplier (supplier_organisation_id),KEY end_date (end_date),KEY status (status)) $c;";
  $sql[]="CREATE TABLE {$t['procurement_documents']} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,procurement_record_id bigint(20) unsigned NOT NULL,document_id varchar(255) DEFAULT NULL,url text NOT NULL,title text DEFAULT NULL,document_type varchar(60) DEFAULT NULL,format varchar(100) DEFAULT NULL,language_code char(5) DEFAULT NULL,date_published datetime DEFAULT NULL,content_hash char(64) DEFAULT NULL,access_status varchar(30) NOT NULL DEFAULT 'unprocessed',created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY (id),UNIQUE KEY record_document (procurement_record_id,document_id),KEY document_type (document_type),KEY content_hash (content_hash)) $c;";
  foreach($sql as $statement){ dbDelta($statement); }
 }
}
