<?php
defined('ABSPATH') || exit;
final class GOI_Core_DB {
 public static function tables(): array { global $wpdb; $p=$wpdb->prefix.'goi_'; return ['organisations'=>$p.'organisations','countries'=>$p.'countries','regions'=>$p.'regions','data_sources'=>$p.'data_sources','opportunities'=>$p.'opportunities','opportunity_sources'=>$p.'opportunity_sources']; }
 public static function install_schema(): void {
  global $wpdb; require_once ABSPATH.'wp-admin/includes/upgrade.php'; $t=self::tables(); $c=$wpdb->get_charset_collate(); $sql=[];
  $sql[]="CREATE TABLE {$t['organisations']} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,uuid char(36) NOT NULL,name varchar(255) NOT NULL,organisation_type varchar(50) NOT NULL DEFAULT 'company',country_code char(2) DEFAULT NULL,website_url text DEFAULT NULL,status varchar(30) NOT NULL DEFAULT 'active',created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY (id),UNIQUE KEY uuid (uuid),KEY country_code (country_code),KEY type_status (organisation_type,status)) $c;";
  $sql[]="CREATE TABLE {$t['countries']} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,iso2 char(2) NOT NULL,iso3 char(3) NOT NULL,name varchar(255) NOT NULL,currency_code char(3) DEFAULT NULL,timezone varchar(64) DEFAULT NULL,latitude decimal(10,7) DEFAULT NULL,longitude decimal(10,7) DEFAULT NULL,status varchar(30) NOT NULL DEFAULT 'active',created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY (id),UNIQUE KEY iso2 (iso2),UNIQUE KEY iso3 (iso3),KEY status (status)) $c;";
  $sql[]="CREATE TABLE {$t['regions']} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,uuid char(36) NOT NULL,country_id bigint(20) unsigned NOT NULL,parent_id bigint(20) unsigned DEFAULT NULL,name varchar(255) NOT NULL,region_type varchar(40) NOT NULL DEFAULT 'region',latitude decimal(10,7) DEFAULT NULL,longitude decimal(10,7) DEFAULT NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY (id),UNIQUE KEY uuid (uuid),KEY country_parent (country_id,parent_id),KEY name (name)) $c;";
  $sql[]="CREATE TABLE {$t['data_sources']} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,uuid char(36) NOT NULL,name varchar(255) NOT NULL,owner_name varchar(255) DEFAULT NULL,source_type varchar(40) NOT NULL,country_code char(2) DEFAULT NULL,base_url text DEFAULT NULL,licence text DEFAULT NULL,reliability decimal(5,2) DEFAULT NULL,status varchar(30) NOT NULL DEFAULT 'active',last_sync_at datetime DEFAULT NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY (id),UNIQUE KEY uuid (uuid),KEY country_status (country_code,status),KEY type_status (source_type,status)) $c;";
  $sql[]="CREATE TABLE {$t['opportunities']} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,uuid char(36) NOT NULL,external_id varchar(255) DEFAULT NULL,title text NOT NULL,description longtext DEFAULT NULL,opportunity_type varchar(50) NOT NULL DEFAULT 'procurement',status varchar(30) NOT NULL DEFAULT 'open',country_code char(2) DEFAULT NULL,region_id bigint(20) unsigned DEFAULT NULL,buyer_organisation_id bigint(20) unsigned DEFAULT NULL,published_at datetime DEFAULT NULL,deadline_at datetime DEFAULT NULL,estimated_value decimal(20,2) DEFAULT NULL,currency_code char(3) DEFAULT NULL,url text DEFAULT NULL,source_updated_at datetime DEFAULT NULL,first_seen_at datetime NOT NULL,last_seen_at datetime NOT NULL,content_hash char(64) DEFAULT NULL,metadata longtext DEFAULT NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY (id),UNIQUE KEY uuid (uuid),UNIQUE KEY source_external (external_id,country_code),KEY deadline_status (deadline_at,status),KEY country_status (country_code,status),KEY buyer (buyer_organisation_id),KEY region (region_id),KEY content_hash (content_hash)) $c;";
  $sql[]="CREATE TABLE {$t['opportunity_sources']} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,opportunity_id bigint(20) unsigned NOT NULL,source_id bigint(20) unsigned NOT NULL,source_record_id varchar(255) DEFAULT NULL,source_url text DEFAULT NULL,observed_at datetime NOT NULL,raw_hash char(64) DEFAULT NULL,PRIMARY KEY (id),UNIQUE KEY opportunity_source (opportunity_id,source_id),KEY source_record (source_id,source_record_id)) $c;";
  foreach($sql as $statement){ dbDelta($statement); }
 }
}
